name: My First Workflow

on: push

jobs: 
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "Welcome to my first GitHub Actions workflow!"
        - name: Display current date and time
          run: date
        - name: list files
          run: ls -la
        - name: Read files
          run: cat ./README.md