name: Generate ASCII Artwork
on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Install cowsay
          run: sudo apt-get install -y cowsay
        - name: execute cowsay CMD
          run: cowsay -f dragon "Run for cover, it's a dragon!" >> dragon.txt
        - name: Test file exists
          run: grep -i "dragon" dragon.txt
        - name: Read FIle
          run: cat dragon.txt
        - name: checkout repo files
          run: ls -la   